version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-collector-minimal
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.minimal.yaml"]
    volumes:
      - ./otel-collector-config.minimal.yaml:/etc/otel-collector-config.minimal.yaml:ro
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP (healthcheck expects this)
      - "13133:13133"  # OTEL Collector health check
    networks:
      - app-network
    environment:
      - NO_WINDOWS_SERVICE=1

networks:
  app-network:
    external: true
